name: testing-and-deployment-pipeline
on: push
jobs:
  testing-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dir

  deployment-pipeline:
    needs: testing-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploying..."

